In [1]:
# Cell 1: Import Libraries

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt
import numpy as np

print("Libraries imported successfully.")

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "c:\Users\Hoang\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [3]:
%pip install torch torchvision matplotlib ipykernel

   ---------------------------------------- 0.0/122.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/122.0 MB 7.2 MB/s eta 0:00:17
    --------------------------------------- 2.4/122.0 MB 7.9 MB/s eta 0:00:16
   - -------------------------------------- 4.2/122.0 MB 7.2 MB/s eta 0:00:17
   - -------------------------------------- 5.8/122.0 MB 7.5 MB/s eta 0:00:16
   -- ------------------------------------- 7.3/122.0 MB 7.4 MB/s eta 0:00:16
   --- ------------------------------------ 9.2/122.0 MB 7.4 MB/s eta 0:00:16
   --- ------------------------------------ 10.7/122.0 MB 7.5 MB/s eta 0:00:15
   ---- ----------------------------------- 12.3/122.0 MB 7.5 MB/s eta 0:00:15
   ---- ----------------------------------- 13.9/122.0 MB 7.5 MB/s eta 0:00:15
   ----- ---------------------------------- 15.5/122.0 MB 7.5 MB/s eta 0:00:15
   ----- ---------------------------------- 17.0/122.0 MB 7.5 MB/s eta 0:00:14
   ------ --------------------------------- 18.9/122.0 MB 7.5 MB/s


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
# Cell 2: Check PyTorch Version

print("PyTorch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.13.0+cpu
CUDA version: None
CUDA available: False


In [10]:
# Cell 3: Device Configuration

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Selected device:", device)

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("GPU is not available. The lab will run on CPU.")

Selected device: cpu
GPU is not available. The lab will run on CPU.


In [11]:
# Cell 4: Tensor Demo

x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.ones((2, 2))

print("Tensor x:\n", x)
print("\nShape:", x.shape)
print("Data type:", x.dtype)
print("Addition:\n", x + y)
print("Matrix multiplication:\n", x @ y)

x = x.to(device)
print("Device:", x.device)

Tensor x:
 tensor([[1., 2.],
        [3., 4.]])

Shape: torch.Size([2, 2])
Data type: torch.float32
Addition:
 tensor([[2., 3.],
        [4., 5.]])
Matrix multiplication:
 tensor([[3., 3.],
        [7., 7.]])
Device: cpu
