# Practice 1: FashionMNIST Classification with PyTorch

This notebook is the first part of the lab. It checks whether PyTorch is ready to use, selects the available device, and shows some basic tensor operations.

## Objectives

- Import the libraries used in the lab.
- Check the installed PyTorch version.
- Select CPU or GPU.
- Practice basic tensor operations.

In [1]:
# Cell 1: Import Libraries

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.


## PyTorch

PyTorch is the main library used in this lab. It will be used to process data, build the neural network, train the model, and evaluate the results.

In [2]:
# Cell 2: Check PyTorch Version

print("PyTorch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.13.0+cpu
CUDA version: None
CUDA available: False


## CPU and GPU

PyTorch can run on both CPU and GPU. A GPU usually makes model training faster because it can handle many calculations at the same time.

If CUDA is not available, the lab will run on the CPU.

In [3]:
# Cell 3: Device Configuration

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Selected device:", device)

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("GPU is not available. Using CPU.")

Selected device: cpu
GPU is not available. Using CPU.


## Tensor

A tensor is the main data structure used in PyTorch. It is similar to a NumPy array and can store vectors, matrices, images, and other numerical data.

In this example, two small tensors are created to test some basic operations.

In [4]:
# Cell 4: Tensor Demo

x = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

y = torch.ones((2, 2))

print("Tensor x:\n", x)
print("\nTensor y:\n", y)

print("\nShape:", x.shape)
print("Data type:", x.dtype)

print("\nAddition:\n", x + y)
print("\nElement-wise multiplication:\n", x * y)
print("\nMatrix multiplication:\n", x @ y)

x = x.to(device)
print("\nTensor device:", x.device)

Tensor x:
 tensor([[1., 2.],
        [3., 4.]])

Tensor y:
 tensor([[1., 1.],
        [1., 1.]])

Shape: torch.Size([2, 2])
Data type: torch.float32

Addition:
 tensor([[2., 3.],
        [4., 5.]])

Element-wise multiplication:
 tensor([[1., 2.],
        [3., 4.]])

Matrix multiplication:
 tensor([[3., 3.],
        [7., 7.]])

Tensor device: cpu
